using System.Text.Json;
using OMP.Ui.Helpers;
using OMP.Ui.Localization;

namespace OMP.Ui.Tests.Helpers;

public class YtDlpSubtitleSelectorTests
{
    [Fact]
    public void SelectSubtitleSidecars_RealSubtitlesTrack_UsesNameAndUrlLangIgnoringCompositeKey()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "subtitles": {
                    "en-US-cvfXDfbeED0": [
                        { "ext": "json3", "url": "https://example.com/timedtext?lang=en-US&fmt=json3", "name": "English (United States) - Captions" },
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en-US&fmt=vtt", "name": "English (United States) - Captions" },
                        { "ext": "srt", "url": "https://example.com/timedtext?lang=en-US&fmt=srt", "name": "English (United States) - Captions" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        var sidecar = Assert.Single(sidecars);
        Assert.Equal("https://example.com/timedtext?lang=en-US&fmt=vtt", sidecar.Url);
        Assert.Equal("en-US", sidecar.Language);
        Assert.Equal("English (United States) - Captions", sidecar.Title);
    }

    [Fact]
    public void SelectSubtitleSidecars_AutomaticCaptions_ListsEveryTranslationAfterTheOriginal()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "automatic_captions": {
                    "de": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=de&kind=asr&fmt=vtt", "name": "German" }
                    ],
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English" }
                    ],
                    "es": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=es&kind=asr&fmt=vtt", "name": "Spanish" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: "fr");

        Assert.Equal(["en", "de", "es"], sidecars.Select(s => s.Language));
        Assert.Equal(string.Format(Strings.OpenUrl_AutoGeneratedSubtitleFormat, "English"), sidecars[0].Title);
        Assert.Equal(string.Format(Strings.OpenUrl_AutoGeneratedTranslatedSubtitleFormat, "German"), sidecars[1].Title);
    }

    [Fact]
    public void SelectSubtitleSidecars_AutomaticCaptions_AppLanguageTranslationComesRightAfterTheOriginal()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "automatic_captions": {
                    "de": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=de&kind=asr&fmt=vtt", "name": "German" }
                    ],
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English" }
                    ],
                    "fr": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=fr&kind=asr&fmt=vtt", "name": "French" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: "fr");

        Assert.Equal(["en", "fr", "de"], sidecars.Select(s => s.Language));
        Assert.Equal(string.Format(Strings.OpenUrl_AutoGeneratedTranslatedSubtitleFormat, "French"), sidecars[1].Title);
    }

    /// <summary>
    /// The real shape of an auto-dubbed video: yt-dlp merges one recognition per audio track into
    /// the same language keys, ordered by YouTube's translation-language list - so the Arabic dub's
    /// untranslated recognition comes before the English original's, and a translated key holds a
    /// translation from each recognition.
    /// </summary>
    [Fact]
    public void SelectSubtitleSidecars_AutoDubbedVideo_PicksTheDeclaredOriginalAndTranslatesFromIt()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "formats": [
                    { "format_id": "251-0", "language": "ar", "language_preference": -1 },
                    { "format_id": "251-1", "language": "en", "language_preference": 10 }
                ],
                "automatic_captions": {
                    "ar-orig": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&kind=asr&fmt=vtt", "name": "Arabic (Original)" }
                    ],
                    "ar": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&kind=asr&fmt=vtt", "name": "Arabic" },
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=ar&kind=asr&fmt=vtt", "name": "Arabic" }
                    ],
                    "en-orig": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English (Original)" }
                    ],
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&tlang=en&kind=asr&fmt=vtt", "name": "English" },
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English" }
                    ],
                    "ru": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&tlang=ru&kind=asr&fmt=vtt", "name": "Russian" },
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&tlang=ru&kind=asr&fmt=vtt", "name": "Russian" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: "ru");

        Assert.Equal("https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", sidecars[0].Url);
        Assert.Equal("en", sidecars[0].Language);
        Assert.Equal("https://example.com/timedtext?lang=en&tlang=ru&kind=asr&fmt=vtt", sidecars[1].Url);
        Assert.Equal("ru", sidecars[1].Language);

        Assert.Contains(sidecars, s => s.Url == "https://example.com/timedtext?lang=ar&kind=asr&fmt=vtt");
        Assert.Contains(sidecars, s => s.Url == "https://example.com/timedtext?lang=en&tlang=ar&kind=asr&fmt=vtt");
        Assert.DoesNotContain(sidecars, s => s.Url.Contains("lang=ar&tlang="));
        Assert.Equal(4, sidecars.Count);
    }

    [Fact]
    public void SelectSubtitleSidecars_NoOriginalAudioFormat_FallsBackToTopLevelLanguage()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "language": "en",
                "automatic_captions": {
                    "ar": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&kind=asr&fmt=vtt", "name": "Arabic" }
                    ],
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        Assert.Equal("en", sidecars[0].Language);
    }

    [Fact]
    public void SelectSubtitleSidecars_NoDeclaredLanguage_FallsBackToTheOrigMarkedRecognition()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "automatic_captions": {
                    "ar": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=ar&kind=asr&fmt=vtt", "name": "Arabic" }
                    ],
                    "en-orig": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English (Original)" }
                    ],
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/timedtext?lang=en&kind=asr&fmt=vtt", "name": "English" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        Assert.Equal("en", sidecars[0].Language);
        Assert.Equal(2, sidecars.Count);
    }

    [Fact]
    public void SelectSubtitleSidecars_CaptionUrlWithoutLangParam_UsesTheDictionaryKey()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "automatic_captions": {
                    "en": [
                        { "ext": "vtt", "url": "https://example.com/live/captions.m3u8" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        var sidecar = Assert.Single(sidecars);
        Assert.Equal("en", sidecar.Language);
        Assert.Equal(string.Format(Strings.OpenUrl_AutoGeneratedSubtitleFormat, "English"), sidecar.Title);
    }

    [Fact]
    public void SelectSubtitleSidecars_OnlyNonVttSrtFormatsAvailable_TrackIsSkipped()
    {
        using var document = JsonDocument.Parse(
            """
            {
                "subtitles": {
                    "en": [
                        { "ext": "json3", "url": "https://example.com/timedtext?lang=en&fmt=json3", "name": "English" },
                        { "ext": "ttml", "url": "https://example.com/timedtext?lang=en&fmt=ttml", "name": "English" }
                    ]
                }
            }
            """);

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        Assert.Empty(sidecars);
    }

    [Fact]
    public void SelectSubtitleSidecars_NoSubtitleFieldsAtAll_ReturnsEmpty()
    {
        using var document = JsonDocument.Parse("{ \"title\": \"No captions here\" }");

        var sidecars = YtDlpSubtitleSelector.SelectSubtitleSidecars(document, appLanguageCode: null);

        Assert.Empty(sidecars);
    }
}
