using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using OMP.Lib.Subtitle;
using OMP.Ui.Localization;

namespace OMP.Ui.Helpers;

internal static class YtDlpSubtitleSelector
{
    private const string OriginalKeySuffix = "-orig";
    private const int OriginalLanguagePreference = 10;

    public static IReadOnlyList<SubtitleSidecarSource> SelectSubtitleSidecars(JsonDocument document, string? appLanguageCode)
    {
        var root = document.RootElement;
        var result = new List<SubtitleSidecarSource>();

        if (root.TryGetProperty("subtitles", out var subtitles) && subtitles.ValueKind == JsonValueKind.Object)
        {
            foreach (var track in subtitles.EnumerateObject())
            {
                if (TryPickTrackFormat(track.Value.EnumerateArray(), out var format))
                {
                    result.Add(BuildSidecar(format));
                }
            }
        }

        if (root.TryGetProperty("automatic_captions", out var automaticCaptions) &&
            automaticCaptions.ValueKind == JsonValueKind.Object)
        {
            result.AddRange(SelectAutomaticCaptions(automaticCaptions, DetectOriginalLanguage(root), appLanguageCode));
        }

        return result;
    }

    /// <summary>
    /// yt-dlp merges every auto-generated caption track YouTube offers into one dictionary keyed by
    /// target language - and an auto-dubbed video has one such track per dubbed audio track, not
    /// just one for the original. So a key's formats can come from several recognitions, and the
    /// first untranslated entry in the dictionary is not necessarily the original language (it's
    /// ordered by YouTube's translation-language list, so e.g. an Arabic dub's recognition sorts
    /// ahead of the English original). The original is identified from the video's own declared
    /// language instead, and translations are only taken from that original's recognition.
    /// </summary>
    private static IEnumerable<SubtitleSidecarSource> SelectAutomaticCaptions(
        JsonElement automaticCaptions, string? originalLanguageCode, string? appLanguageCode)
    {
        var recognitions = new List<AutomaticCaption>();
        var translations = new List<AutomaticCaption>();

        foreach (var track in automaticCaptions.EnumerateObject())
        {
            if (track.Name.EndsWith(OriginalKeySuffix, StringComparison.Ordinal) ||
                track.Value.ValueKind != JsonValueKind.Array)
            {
                continue;
            }

            foreach (var format in PickTrackFormats(track.Value))
            {
                var url = format.GetProperty("url").GetString()!;
                var sourceLanguage = GetQueryParam(url, "lang") ?? track.Name;
                var targetLanguage = GetQueryParam(url, "tlang");

                var caption = new AutomaticCaption(format, sourceLanguage, targetLanguage ?? sourceLanguage);
                (string.IsNullOrEmpty(targetLanguage) ? recognitions : translations).Add(caption);
            }
        }

        recognitions = recognitions.DistinctBy(c => c.Language, StringComparer.OrdinalIgnoreCase).ToList();

        var original = FindOriginal(automaticCaptions, recognitions, originalLanguageCode);
        if (original is null)
        {
            yield break;
        }

        yield return BuildAutomaticCaptionSidecar(original, Strings.OpenUrl_AutoGeneratedSubtitleFormat);

        var originalTranslations = translations
            .Where(c => SameLanguage(c.SourceLanguage, original.Language))
            .Where(c => !SameLanguage(c.Language, original.Language))
            .DistinctBy(c => c.Language, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var appTranslation = originalTranslations.FirstOrDefault(c => SameLanguage(c.Language, appLanguageCode));
        if (appTranslation is not null)
        {
            yield return BuildAutomaticCaptionSidecar(appTranslation, Strings.OpenUrl_AutoGeneratedTranslatedSubtitleFormat);
        }

        var otherRecognitions = recognitions
            .Where(c => c != original)
            .Select(c => BuildAutomaticCaptionSidecar(c, Strings.OpenUrl_AutoGeneratedSubtitleFormat));

        var otherTranslations = originalTranslations
            .Where(c => c != appTranslation)
            .Select(c => BuildAutomaticCaptionSidecar(c, Strings.OpenUrl_AutoGeneratedTranslatedSubtitleFormat));

        foreach (var sidecar in otherRecognitions.Concat(otherTranslations)
                     .OrderBy(s => s.Title, StringComparer.CurrentCultureIgnoreCase))
        {
            yield return sidecar;
        }
    }

    /// <summary>
    /// yt-dlp marks the original audio track's formats with <c>language_preference</c> 10 (every
    /// auto-dub gets -1); the top-level <c>language</c> is only a fallback, since it describes
    /// whichever format happened to be selected and can be a joined value like <c>en+ar</c>.
    /// </summary>
    private static string? DetectOriginalLanguage(JsonElement root)
    {
        if (root.TryGetProperty("formats", out var formats) && formats.ValueKind == JsonValueKind.Array)
        {
            foreach (var format in formats.EnumerateArray())
            {
                if (format.TryGetProperty("language_preference", out var preference) &&
                    preference.ValueKind == JsonValueKind.Number &&
                    preference.GetInt32() >= OriginalLanguagePreference &&
                    format.TryGetProperty("language", out var language) &&
                    language.ValueKind == JsonValueKind.String)
                {
                    return language.GetString();
                }
            }
        }

        return root.TryGetProperty("language", out var rootLanguage) &&
               rootLanguage.ValueKind == JsonValueKind.String &&
               rootLanguage.GetString() is { } value &&
               !value.Contains('+')
            ? value
            : null;
    }

    private static AutomaticCaption? FindOriginal(
        JsonElement automaticCaptions, IReadOnlyList<AutomaticCaption> recognitions, string? originalLanguageCode)
    {
        if (recognitions.FirstOrDefault(c => SameLanguage(c.Language, originalLanguageCode)) is { } declared)
        {
            return declared;
        }

        foreach (var track in automaticCaptions.EnumerateObject())
        {
            if (track.Name.EndsWith(OriginalKeySuffix, StringComparison.Ordinal))
            {
                var language = track.Name[..^OriginalKeySuffix.Length];
                if (recognitions.FirstOrDefault(c => SameLanguage(c.Language, language)) is { } marked)
                {
                    return marked;
                }
            }
        }

        return recognitions.FirstOrDefault();
    }

    private static IEnumerable<JsonElement> PickTrackFormats(JsonElement formats)
    {
        // A key merged from several recognitions holds one run of formats per recognition, so the
        // preferred format is picked per (source, target) pair rather than once for the whole key.
        return formats.EnumerateArray()
            .Where(f => f.TryGetProperty("url", out _) && f.TryGetProperty("ext", out _))
            .GroupBy(f =>
            {
                var url = f.GetProperty("url").GetString()!;
                return (GetQueryParam(url, "lang"), GetQueryParam(url, "tlang"));
            })
            .Select(group => TryPickTrackFormat(group, out var format) ? format : (JsonElement?)null)
            .OfType<JsonElement>();
    }

    private static bool SameLanguage(string? left, string? right) =>
        NormalizeToTwoLetter(left) is { } l &&
        NormalizeToTwoLetter(right) is { } r &&
        l.Equals(r, StringComparison.OrdinalIgnoreCase);

    private static bool TryPickTrackFormat(IEnumerable<JsonElement> formats, out JsonElement format)
    {
        JsonElement? vtt = null;
        JsonElement? srt = null;

        foreach (var candidate in formats)
        {
            if (!candidate.TryGetProperty("ext", out var extElement))
            {
                continue;
            }

            switch (extElement.GetString())
            {
                case "vtt":
                    vtt ??= candidate;
                    break;
                case "srt":
                    srt ??= candidate;
                    break;
            }
        }

        if (vtt is { } vttFormat)
        {
            format = vttFormat;
            return true;
        }

        if (srt is { } srtFormat)
        {
            format = srtFormat;
            return true;
        }

        format = default;
        return false;
    }

    private static SubtitleSidecarSource BuildSidecar(JsonElement format)
    {
        var url = format.GetProperty("url").GetString()!;
        var name = format.TryGetProperty("name", out var nameElement) ? nameElement.GetString() : null;
        var language = GetQueryParam(url, "lang");

        return new SubtitleSidecarSource(url, language, name);
    }

    private static SubtitleSidecarSource BuildAutomaticCaptionSidecar(AutomaticCaption caption, string titleFormat)
    {
        var url = caption.Format.GetProperty("url").GetString()!;
        var name = caption.Format.TryGetProperty("name", out var nameElement) ? nameElement.GetString() : null;
        var title = string.Format(titleFormat, name ?? LanguageDisplay.NativeName(caption.Language));

        return new SubtitleSidecarSource(url, caption.Language, title);
    }

    private static string? GetQueryParam(string url, string paramName)
    {
        var queryStart = url.IndexOf('?');
        if (queryStart < 0)
        {
            return null;
        }

        foreach (var pair in url[(queryStart + 1)..].Split('&'))
        {
            var separator = pair.IndexOf('=');
            if (separator < 0 || !pair.AsSpan(0, separator).Equals(paramName, StringComparison.Ordinal))
            {
                continue;
            }

            return Uri.UnescapeDataString(pair[(separator + 1)..]);
        }

        return null;
    }

    private static string? NormalizeToTwoLetter(string? languageCode)
    {
        if (string.IsNullOrEmpty(languageCode))
        {
            return null;
        }

        try
        {
            return CultureInfo.GetCultureInfo(languageCode).TwoLetterISOLanguageName;
        }
        catch (CultureNotFoundException)
        {
            return languageCode;
        }
    }

    private sealed record AutomaticCaption(JsonElement Format, string SourceLanguage, string Language);
}
