<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)..\stylecop.json" Link="stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <Content Condition="$([MSBuild]::IsOSPlatform('Windows'))" Include="Libs\win\**">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
